image: localhost:5000/cpp-runner:latest

build-job:
  stage: build
  script:
    - echo "Hello, $GITLAB_USER_LOGIN!"
    - add-apt-repository --yes ppa:ubuntu-sdk-team/ppa
    - apt-get update -qq
    - apt-get install qt5-default qttools5-dev-tools
    - gcc --version
    - cmake --version
    - qmake -v
    - mkdir build && cd build
    - cmake ..
    - make
    - cd tests
    - ./tests
